### ISSUE TITLE
Shortcut on Chromebook

### ISSUE THREAD

**Issue by H644b** [andreibachim/shortcut#5] opened 2023-09-21 00:28 UTC
Does Shortcut work on Chromebook? If so then can someone help me with a bug I am experiencing. I basically installed Shortcut through flathub on to my chromebook running linux and whenever I am done with the name and the file directory's, I click the next button and it just crashes and does nothing.

**Comment by H644b** [comment] 2023-09-21 00:55
For now I am forced to do it the Manual Way until I get an answer

**Comment by andreibachim** [comment] 2023-09-21 03:32
This app was designed to integrate properly and work with the GNOME desktop environment, so I did not test it on Chromebooks. 

But I will look into it anyway and see if I can resolve the issue. I suspect there might be a problem with resolving the path to where the file needs to be saved.

**Comment by andreibachim** [comment] 2023-09-21 11:33
I looked into the problem and it turns out that chromebooks do not have the `$HOME/.local/share/applications/` directory created by default. I will include a fix to have Shortcut create the directory if it is not already present in the next release.

Meanwhile, if you want to use Shortcut, you can run the following command in a terminal and the crash will no longer occur:
`mkdir ~/.local/share/applications`

**Comment by andreibachim** [comment] 2023-09-22 10:43
version v3.1 is up on flathub, this should resolve this issue.

**Closed as completed by andreibachim** 2023-09-22 10:43 UTC
Labels: bug

**Comment by H644b** [comment] 2023-09-24 13:16
Thanks
